[env:pixmob_nova_esp32c3]
;extends = env:esp32c3dev
platform = espressif32
board = seeed_xiao_esp32c3
;board = esp32-c3-devkitm-1
custom_usermods =
  ;${env:esp32c3dev.custom_usermods}
  PixMob_Receiver
build_flags =
  ;${env:esp32c3dev.build_flags}
  -D WLED_RELEASE_NAME="PIXMOB_NOVA"
  -D PIXMOB_NOVA_EVENT_RECEIVER=1
